image: docker:latest

cache:
  paths:
    - vendor/

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test

php-cs:
  image: pavelkrauchuk/php-fpm-8.2-symfony
  stage: test
  script:
    - ls
    # - docker run -d pavelkrauchuk/php-fpm-8.2-symfony -e "APP_ENV=test" --name php-fpm -v ./:/symfony
    # - docker exec -T php-fmp composer install
    # - docker-compose -f docker-compose.test.yml up --build -d
    # - docker-compose -f docker-compose.test.yml exec -T php-fpm composer install
    # - docker-compose -f docker-compose.test.yml exec -T php-fpm php ./vendor/bin/phpcs --report=junit --report-file=php_cs_results.xml ./src
  artifacts:
    reports:
      junit: php_cs_results.xml
    when: always
