image: docker:latest

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test

php-cs:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --build -d
    - docker-compose -f docker-compose.test.yml exec -T php-fpm composer install
    - docker-compose -f docker-compose.test.yml exec -T php-fpm php ./vendor/bin/phpcs ./src
