image: docker:latest

cache:
  paths:
    - vendor/

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - code-quality

composer:
  stage: build
  image: pavelkrauchuk/php-fpm-8.2-symfony
  variables:
    APP_ENV: test
  script:
    - composer install

php-cs:
  stage: code-quality
  image: pavelkrauchuk/php-fpm-8.2-symfony
  variables:
    APP_ENV: test
  script:
    - php ./vendor/bin/phpcs --report=junit --report-file=php_cs_results.xml ./src
  artifacts:
    reports:
      junit: php_cs_results.xml
    when: always
