stages:
  - test

hello_world:
  stage: test
  script:
    - echo "Starting test environment"
    - docker-compose -f docker-compose.test.yml down
    - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
