stages:
  - test

default:
  before_script:
    - echo "Starting test environment"
    - docker-compose -f docker-compose.test.yml up --build -d
  after_script:
    - echo "Stopping test environment"
    - docker-compose -f docker-compose.test.yml down

test-job:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml exec -T php-fpm php -v
