version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/symfony
    container_name: testtask-symfony-prod-nginx
    restart: always
    ports:
      - "80:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/symfony
    container_name: testtask-symfony-prod-php-fpm
    environment:
      APP_ENV: prod
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    container_name: testtask-symfony-prod-postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: symfony
    ports:
      - "5432"

volumes:
  postgres:
