version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/symfony
    container_name: testtask-symfony-nginx
    restart: always
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/symfony
    container_name: testtask-symfony-php-fpm
    environment:
      APP_ENV: dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    container_name: testtask-symfony-postgres
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: symfony
    ports:
      - "5434:5432"

volumes:
  postgres:

